Level 2
lexstronger/movies-explorer-frontend pull request #1
Opened 2023-10-19 17:29 UTC by lexstronger

2023-10-19 18:22 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- https://yadi.sk/d/aRaLtB498U6-AQ https://yadi.sk/d/SPuOgRmp7_40xQ https://yadi.sk/d/b3Bd4W8zJ7rLvw у контента в макете используется letter-spacing с отрицательным значением, необходимо скорректировать по всему проекту
	- Карточки с фильмами - нет кнопок Сохранено и Удалить по макету

	**Главная**
	- 1280 https://yadi.sk/d/2fU3omoWYCSvsw https://yadi.sk/d/0H4MbxZM1FbVUg (стрелочки отличаются от макета на всех разрешениях)
	- 768 https://yadi.sk/d/7_hcBB1OfXStKA
	- 320 https://yadi.sk/d/pLL2T3gj_ORaBQ https://yadi.sk/d/2CVxvG58q2Ebjg https://yadi.sk/d/tV6yY0Pk06BMlQ

	**Фильмы**
	- 1280 https://yadi.sk/d/n0DmZZIKdpSNGw
	- 768 https://yadi.sk/d/-emmcn3OY8mj8Q
	- 320 https://yadi.sk/d/bycW-qFkbth8BA https://yadi.sk/d/nWSvpDKbe-UwgA

	**Сохраненные**
	- https://yadi.sk/d/sFeEdYV-0_AzCA отступ до подвала на всех разрешениях, а также кнопки Еще по макету нет

	**Меню**
	- 768 https://yadi.sk/d/FFBsDsf45rlkOA
	- 320 https://yadi.sk/d/6wOwmrBUTfRrhw

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [ ] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

	- Выйти из аккаунта - хорошо бы при нажатии переходить на Главную/Вход

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/Ce5eOAeJ0YxG6Q (Фильмы. Профиль) в проекте есть ошибки БЭМ, воспользуйтесь валидатором для проверки https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/q6tyIC92d_oD_g https://yadi.sk/d/t_ZjEmjJ3eaHcQ В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи
	- https://yadi.sk/d/lMCkwAlr27a20Q контент следует сделать отзывчивым на всех устройствах. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, шапка прижата к верху, футер к низу. Можно лучше на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- Проект содержит ошибки валидации, воспользуйтесь валидатором для проверки https://validator.w3.org/#validate_by_input
	- Каждой отдельной странице нужен заголовок 1 уровня (Вход/Рег/Профиль)
	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Вход/Рег/Профиль/404)
	- popup__links - навигационные списки хорошо оформить селектором nav
	- portfolio__arrow - используйте селектор span и ариа атрибут aria-hidden="true" для того, чтобы скрыть декоративные элементы от скринридеров тем самым улучшив семантику.
	- promo__image - также можно декоративное изображение скрыть от скринридеров. Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- promo__heading - главный заголовк оформите 1 уровнем

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- Всем кнопкам и ссылкам в проекте требуется добавить ховер эффект и курсор если стоит не pointer

- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

	- Окно Входа и Регистрации выглядит как один компонент, по функционалу и визуально не сильно отличается по макету. Можно объединить.
	- кнопка профиля также может быть выделена в БЭМ блок.
	- логотип также в проекте один, можно оформить одним блоком.

- [ ] <!--2.14--> Шрифты подключены через @font-face.

	- В проекте рендерится Ариал https://yadi.sk/d/VfrCHm4W782F2Q

- [ ] <!--2.14--> Иконки экспортированы в формате SVG.

	- promo-logo.svg - экспортируйте фоновое изображение в формате png, рамер будет меньше

- [ ] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.

	- Поиск, профиль - Всем полям следует стилизовать состояния focus и outline по макету или на свое усмотрение, чтобы при переключении через tab или установлении фокуса, было визуально выделено поле.

- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- У формы должны быть валидированы поля, при нажатии на кнопку выдавать ошибку валидации, только когда все поля валидны производить вход.
	- Всем полям следует установить placeholder со значениями, напр., `placeholder="Ваше имя..."`
	- Для тегов `<form>` так же следует заполнить атрибут name

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 45

## Доп. Комментарии:
	- <html lang="en"> - язык проекта русский

2023-10-23 11:36 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово второе ревью на Ваш проект. Хорошая работа, много пунктов засчитано.
Баллов пока недостаточно, для того, чтобы его принять, зато есть возможность улучшить работу и получить максимальный балл. Уверена у Вас все получится!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- В проекте рендерится Ариал https://yadi.sk/d/VfrCHm4W782F2Q
	- https://yadi.sk/d/dwFcFXNinm1Czg https://yadi.sk/d/dzUobT4DxLDHCQ у контента в макете используется letter-spacing с отрицательным значением, необходимо скорректировать по всему проекту

	**Главная**
	- 1280 https://yadi.sk/d/dwFcFXNinm1Czg
	- 768 https://yadi.sk/d/EGCMTJeKhU_HRA https://yadi.sk/d/PgKb9enZlUf1RQ
	- 320 https://yadi.sk/d/FwQvgPWPTMCweQ https://yadi.sk/d/OL-RNQjNepYAnQ https://yadi.sk/d/7qU5D369--iJ7w

	**Фильмы**
	- 320 https://yadi.sk/d/pr4iFToScEtK9Q

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- Фильмы https://yadi.sk/d/EsySvDtfNCY5JQ - сохраняются небольшие ошибки БЭМ, воспользуйтесь валидатором для проверки https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/q6tyIC92d_oD_g В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/vLtXFQSDhItJeA Проект содержит ошибки валидации, воспользуйтесь валидатором для проверки https://validator.w3.org/#validate_by_input
	- promo__image - также можно декоративное изображение скрыть от скринридеров добавив атрибут aria-hidden. Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

	- Окно Входа и Регистрации выглядит как один компонент, по функционалу и визуально не сильно отличается по макету. Можно объединить.
	- кнопка профиля также может быть выделена в БЭМ блок.
	- логотип также в проекте один, можно оформить одним блоком.

- [ ] <!--2.14--> Шрифты подключены через @font-face.

	- В проекте рендерится Ариал https://yadi.sk/d/VfrCHm4W782F2Q

- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- У формы должны быть валидированы поля, при нажатии на кнопку выдавать ошибку валидации, только когда все поля валидны производить вход.

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 64

2023-10-24 18:07 UTC, lexstronger commented
P.S. прошу заметить, что при проверке perfectpixel'ем Arial не рендерится, рендерится Inter. В этом можно убедиться, если проверить страницу 404 на экране 768 пикселей. Должно быть, очередной недочет макета. Шрифты, на мой взгляд, установлены верно.

2023-10-25 07:22 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
У Вас получилась отличная работа. Поздравляю Ваш проект принят, желаю Вам дальнейших успехов во всех начинаниях!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- https://yadi.sk/d/qZIp6xIbvRNiAg В проекте еще рендерится Ариал, Вы его не импортируете никуда https://yadi.sk/d/ob2FFNweplmZzQ, а рендерится у Вас он потому, что он, скорее всего, в системе установлен в папке /fonts и это Вас путает.
	- После подключения Вам следует пройтись по текстовым элементам и скорректировать по макету (размер, толщину, высоту строки, и межбуквенное расстояние)

	С Интером - https://yadi.sk/d/a093e1V0_g81Zw https://yadi.sk/d/1X2XMMP3Bc4vww https://yadi.sk/d/KeJgvCSwsd_2fA https://yadi.sk/d/IXpt_U2k_RL2BA https://yadi.sk/d/SXhZ0jDXdekJ4w и так далее по макетам

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [x] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [x] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

	- Окно Входа и Регистрации выглядит как один компонент, по функционалу и визуально не сильно отличается по макету. Можно объединить.
	- кнопка профиля также может быть выделена в БЭМ блок.
	- логотип также в проекте один, можно оформить одним блоком.

- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 86

2023-10-25 16:20 UTC, merged